import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.net.*;
import java.lang.Math;  

class validation {
    
    private int  ping ;
    validation () {
        ping = (int) (Math.random() * (100000 - 1000 + 1) + 1000);
        
    }
    boolean check (Socket clientSocket) {
        try {
            DataOutputStream dOut = new DataOutputStream(clientSocket.getOutputStream());
            String pingInString = Integer.toString(ping);
            
            
            byte[] buff = new byte[1024];
            for (int i =0; i<pingInString.length();i++) {
                buff[i] = (byte)pingInString.charAt(i);
            }
            dOut.write(buff);
            dOut.flush();
            pingInString = new String(buff);

            System.out.println("Generated by CLient :"+pingInString+" size : "+ pingInString.length());
            
            DataInputStream dIn = new DataInputStream(clientSocket.getInputStream());
            
            buff = new byte[1024];
            dIn.read(buff);
            
            String fromServer = new String(buff);
            
            System.out.println("Came from Server "+ fromServer+" size : "+ fromServer.length());
        
            if (buff[0] == (byte)0) {
                // System.out.println("Hitting 0");
                return false;
            } else if (fromServer.equals(pingInString)) {
                return true;
            } else {
                return false;
            }



        } catch (Exception e) {
            System.out.println(e);
            return false;
        }

    }
}
class client {
    
    public static void main(String[] args) {
        int cnt = 0;
        while(cnt <55) {
        try {
            Socket clientSock = new Socket("127.0.0.1",9001);
            validation vald = new validation();
            if ( vald.check(clientSock) == true )  {
                System.out.println("Ok! Ping Checked!");
                System.out.println("You can Now Connected to server !");
                
                DataOutputStream dOut = new DataOutputStream(clientSock.getOutputStream());
                
                String msg ="Hi ! there ";

                dOut.write(msg.getBytes());
                dOut.flush();
                dOut.close();

            } else {
                System.out.println("Oops! Failed to check Ping!");
            }
            
            clientSock.close();            

        } catch (Exception e) {
            System.out.println("Exception occured in "+e);
        }
        cnt ++;
    }
        
    }
}
/*
 DataInputStream dIn = new DataInputStream(sock.getInputStream());
        byte[] buff = new byte[1024];
        dIn.read(buff);
        if (buff[0] == (byte)0) {
            return ;
        } else {
        String temp = new String(buff);
        System.out.println("Client :"+temp+temp.length());
        System.out.flush();
 */